# Docker Compose file for local testing and production
version: '3.8'

services:
  spelwijsheid:
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
